# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hVJBWSNNxzaBK82iTF62vMtLx8UXFD3x
"""

try:
  import streamlit as st
except ModuleNotFoundError:
  import os
  os.system("pip install streamlit")
  import streamlit as st

import pandas as pd
import plotly.express as px

df=pd.read_csv('Advertising_F.csv')
df.head()

#show admin stuff
st.title("Advertising Effectiveness Dashboard_AnyceR")
st.sidebar.header("Filters")
x_var=st.sidebar.selectbox("X-Axis",['TV', 'Radio', 'newspaper'])
y_var=st.sidebar.selectbox("Y-Axis",['sales'])
#Shows scatter plot
fig=px.scatter(df,x=x_var,y=y_var,trendline='ols')
st.plotly_chart(fig)
#shows dataframe
st.write('### Data Frame')
st.dataframe(df)

#lets show a map
st.title('Map')
fig=px.scatter_mapbox(df,lat='latitude',lon='longitude',color='sales',
                      size='TV', hover_name='City')
fig.update_layout(mapbox_style="carto-positron")
st.plotly_chart(fig)
